Compiling on linux: MD; fix typo for linking
bytecodealliance/lucet pull request #600
Opened 2020-11-06 16:33 UTC by Horki

Fix 'typo' linking path for "wasi sysroot"

`sudo ln -s /opt/wasi-sdk-*/share/wasi-sysroot /opt/wasi-sysroot`
=>
`sudo ln -s /opt/wasi-sdk-11.0/share/wasi-sysroot /opt/wasi-sysroot`

2020-11-06 16:42 UTC, jedisct1 commented
Hi!

This is not a typo :)

`*` is replaced by the shell with any file matching the pattern.

Using this in the documentation instead of hardcoding a specific version helps the instructions stay relevant even as new versions of the SDK are released.

2020-11-06 16:47 UTC, jedisct1 commented
Just noticed that the previous lines hardcode version numbers. Since the whole paragraph would need to be updated on a new release anyway, we can indeed hardcode that one as well.

A better alternative would be to retrieve the latest version using the `/latest` API as done by most update scripts. But that can be done later.

Thanks!

2020-11-06 16:47 UTC, jedisct1 approved these changes

2020-11-06 18:08 UTC, Horki commented
@jedisct1 when I use '*' with GNU ln (v8.32), I receive an error
` no matches found: /opt/wasi-sdk-*/share/wasi-sysroot`

2020-11-06 19:34 UTC, pchickey commented
Thanks for this fix. The CI failures are due to `cargo audit` and have been fixed upstream - can you pleaserebase on or merge with `main`?

2020-11-06 19:56 UTC, Horki commented
@pchickey rebased and pushed

2020-11-06 21:40 UTC, pchickey approved these changes

2020-11-06 21:44 UTC, pchickey requested changes
It appears your rebased added a bunch of commits to your branch that are already merged into main - not sure what went wrong here.

2020-11-07 08:19 UTC, Horki commented
@pchickey fixed

2020-11-09 18:26 UTC, merged

2020-11-09 18:26 UTC, pchickey commented
Thanks!